/**
 * Blog posts 1–50 (categories: getting-started, feed-mastery, personal-branding,
 * portfolio-projects, launch-strategy).
 * angle = unique, post-specific intro paragraph. focus = topic phrase used in sections.
 */
export const posts1 = [
  /* ---------------- getting-started (1–10) ---------------- */
  {
    slug: 'create-peermeld-account-guide',
    category: 'getting-started',
    title: 'How to Create a Peermeld Account in Under 2 Minutes (2026 Guide)',
    desc: 'Step-by-step Peermeld sign-up guide: Google sign-in, what data is used, and everything your new account unlocks — feed, subdomains, streaks and rewards.',
    tags: ['peermeld account', 'sign up', 'google sign in', 'getting started', 'peermeld guide'],
    focus: 'creating your Peermeld account',
    angle: 'There is no form, no password, and no verification email limbo — Peermeld runs entirely on Sign in with Google, which means your professional identity is literally two clicks away. But the choices you make in those two minutes (which Google account, which name) echo for years. This guide makes sure you make them deliberately.',
  },
  {
    slug: 'claim-yourname-peermeld-subdomain',
    category: 'getting-started',
    title: 'Claim yourname.peermeld.com Before Someone Else Does (Full Walkthrough)',
    desc: 'How to check availability and claim your free Peermeld subdomain, the naming rules (4+ characters, no pure numbers), and how the SEO preview works.',
    tags: ['peermeld subdomain', 'custom domain', 'yourname.peermeld.com', 'personal branding', 'SEO'],
    focus: 'claiming your Peermeld subdomain',
    angle: 'Subdomains on Peermeld are first-come, first-served — and unlike handles on most platforms, this one is a real domain that Google indexes independently. Claiming yours takes about ninety seconds, but choosing the right name deserves a few careful minutes. Here is the complete walkthrough, including the naming rules and the SEO preview most people skip.',
  },
  {
    slug: 'peermeld-profile-setup-checklist',
    category: 'getting-started',
    title: 'The Complete Peermeld Profile Setup Checklist (15 Items, 10 Minutes)',
    desc: 'A printable Peermeld profile checklist: avatar, GIF banner, headline formula, bio keywords, link, company badge and the three tabs visitors always check.',
    tags: ['peermeld profile', 'profile setup', 'checklist', 'headline', 'bio'],
    focus: 'setting up a complete Peermeld profile',
    angle: 'Most profiles fail not from bad content but from missing pieces — a default banner here, an empty link field there. This checklist is the version we wish existed when we joined: fifteen items, in order, each with the one-line reason it exists. Print it, do it once, and never think about profile setup again.',
  },
  {
    slug: 'peermeld-first-post-guide',
    category: 'getting-started',
    title: 'Your First Post on the Peermeld Feed: A Beginner’s Walkthrough',
    desc: 'Exactly what to write in your first Peermeld post, with real examples from the live feed, attachment tips and the follow-up moves that turn one post into a network.',
    tags: ['first post', 'peermeld feed', 'intro post', 'posting guide', 'community'],
    focus: 'publishing your first post',
    angle: 'First posts carry weird pressure — they feel permanent and public, because they are. The good news: Peermeld’s builder community has a strong convention of welcoming honest intros. This guide gives you the exact structure that works, pulled from real first posts on the live feed (like the AtroUI intro that drew cheers and contributors).',
  },
  {
    slug: 'first-week-on-peermeld',
    category: 'getting-started',
    title: '10 Things to Do in Your First Week on Peermeld',
    desc: 'The optimal first-week Peermeld plan: account, subdomain, profile, intro post, 10 follows, project setup and the habits that start your streak compounding.',
    tags: ['first week', 'peermeld plan', 'onboarding', 'new users', 'streak'],
    focus: 'your first week on Peermeld',
    angle: 'A first week sets trajectories. Do it randomly and you’ll have a thin profile that underperforms for months; do it with this ten-item plan and you’ll exit the week with a claimed subdomain, a live streak, your first followers and a feed that already feels like yours. Each item takes less than fifteen minutes.',
  },
  {
    slug: 'peermeld-google-signin-explained',
    category: 'getting-started',
    title: 'Peermeld’s Google Sign-In: What Data Is Used and Why It’s Safe',
    desc: 'What Peermeld reads from your Google account, how the official Google data policy works, and how to choose which account to link for your professional identity.',
    tags: ['google sign in', 'privacy', 'google data policy', 'peermeld account', 'security'],
    focus: 'understanding Peermeld’s Google sign-in and data use',
    angle: 'OAuth buttons deserve healthy suspicion — what exactly is the app reading? In Peermeld’s case the answer is refreshingly small, and it’s documented in a public Google data policy. This article walks through the data flow in plain language and helps you decide which Google account belongs with your professional presence.',
  },
  {
    slug: 'peermeld-username-vs-subdomain-vs-display-name',
    category: 'getting-started',
    title: 'Peermeld Username vs. Subdomain vs. Display Name: What’s the Difference?',
    desc: 'The three identity layers of Peermeld explained — @username, display name and yourname.peermeld.com — and how to align them for maximum discoverability.',
    tags: ['username', 'display name', 'subdomain', 'identity', 'branding'],
    focus: 'Peermeld’s three identity layers',
    angle: 'New members regularly conflate three different things: the display name on your profile, the @username in your URL, and the subdomain you claim. They serve different purposes, they have different rules, and aligning them is one of the highest-ROI branding moves on the platform. Here is the clean mental model.',
  },
  {
    slug: 'peermeld-onboarding-mistakes',
    category: 'getting-started',
    title: '7 Onboarding Mistakes New Peermeld Users Make (And How to Avoid Them)',
    desc: 'The most common Peermeld beginner mistakes — posting before profiling, skipping the subdomain, syndicated content — and the exact fixes for each one.',
    tags: ['mistakes', 'onboarding', 'new users', 'peermeld tips', 'best practices'],
    focus: 'avoiding the classic onboarding mistakes',
    angle: 'We watched hundreds of members join Peermeld, and the same seven mistakes keep appearing — each one quietly tax-collecting growth for months before anyone notices. None require skill to avoid, only awareness. Here is the list, with the specific fix for each, so your first month doesn’t pay the tuition others already paid.',
  },
  {
    slug: 'is-peermeld-free',
    category: 'getting-started',
    title: 'Is Peermeld Free? Every Feature You Get Without Paying a Cent',
    desc: 'A complete inventory of Peermeld’s free tier: the Feed, custom subdomain, portfolio, projects, Launch, directory, streaks, Peers Wallet and rewards.',
    tags: ['free', 'pricing', 'features', 'peermeld review', 'comparison'],
    focus: 'everything Peermeld gives you for free',
    angle: 'When a platform gives away a custom subdomain, a portfolio engine and a launch leaderboard, the obvious question is “where’s the paywall?” We went feature by feature through Peermeld’s current offering so you can see exactly what’s free today — and the answer is essentially the entire platform.',
  },
  {
    slug: 'peermeld-terminology-explained',
    category: 'getting-started',
    title: 'Peermeld Terminology Explained: Feed, Sources, Streaks, Wallet & 20 More Terms',
    desc: 'Every Peermeld term a beginner bumps into — Source accounts, Meld Spaces, Project Rooms, Sera Legacy, Top Streaks, Peers Wallet — defined in plain language.',
    tags: ['glossary', 'terminology', 'beginners', 'peermeld terms', 'reference'],
    focus: 'decoding Peermeld’s vocabulary',
    angle: 'Every platform invents its own vocabulary, and Peermeld’s is unusually rich — Meld Spaces, Sera Legacy, the Peers Wallet. Bookmark this plain-language dictionary; it’s the article you’ll send to the friend you invite next month when they ask what a Source account is.',
  },

  /* ---------------- feed-mastery (11–20) ---------------- */
  {
    slug: 'peermeld-feed-explained',
    category: 'feed-mastery',
    title: 'The Peermeld Feed Explained: Newest, Trending & Following (Complete Guide)',
    desc: 'A complete tour of peermeld.com/feed — the composer, the three tabs, Filters, upvotes, comments and Source accounts — plus how each piece fits your growth.',
    tags: ['peermeld feed', 'feed guide', 'trending', 'newest', 'following'],
    focus: 'the Peermeld Feed end to end',
    angle: 'You could use the Peermeld Feed for months on autopilot and never activate half its machinery. This is the guided tour we give new team members: what each tab really optimises for, what the composer renders, and how the same post travels through three different distribution layers in its first hour.',
  },
  {
    slug: 'peermeld-trending-tab-how-to-rank',
    category: 'feed-mastery',
    title: 'How Peermeld’s Trending Tab Works (And How to Get Your Post On It)',
    desc: 'The observable mechanics of Peermeld’s Trending tab — engagement velocity, comments and timing — with a repeatable recipe for trending posts.',
    tags: ['trending', 'algorithm', 'peermeld feed', 'growth', 'viral'],
    focus: 'ranking on the Trending tab',
    angle: 'Peermeld doesn’t publish its ranking formula, but Trending is refreshingly legible if you watch it daily: velocity beats volume, comments beat upvotes, and newcomers trend beside the founder weekly. This article assembles the observable evidence into a recipe you can actually execute.',
  },
  {
    slug: 'peermeld-post-ideas',
    category: 'feed-mastery',
    title: '21 Post Ideas That Consistently Perform on the Peermeld Feed',
    desc: 'Never stare at the composer again: 21 proven Peermeld post formats, from changelogs and build questions to tool takes, with examples and templates.',
    tags: ['post ideas', 'content ideas', 'peermeld feed', 'writing', 'content strategy'],
    focus: 'finding post ideas that work',
    angle: 'Blank-composer syndrome kills more Peermeld careers than bad writing. These 21 formats are reverse-engineered from what actually trends — from the Peermeld team’s numbered changelog to the two-line tool take. Steal the templates, fill them with your work, and the daily post stops being a chore.',
  },
  {
    slug: 'peermeld-upvotes-avatars-psychology',
    category: 'feed-mastery',
    title: 'Why Peermeld Shows Upvoter Avatars (And How to Use It for Networking)',
    desc: 'Peermeld displays the avatars of users who upvoted each post. Here’s the social psychology behind the feature and the networking plays it unlocks.',
    tags: ['upvotes', 'avatars', 'networking', 'engagement', 'psychology'],
    focus: 'the visible-upvoters feature',
    angle: 'When Peermeld added upvoter avatars to posts, it quietly changed upvoting from anonymous applause into visible association. Your face on someone’s launch post is now a micro-act of networking — and their upvoters are your warmest possible outreach list. Here is how thoughtful members are using it.',
  },
  {
    slug: 'peermeld-comment-strategy',
    category: 'feed-mastery',
    title: 'The Peermeld Comment Strategy That Grows Followers Faster Than Posting',
    desc: 'How to write Peermeld comments that earn likes, replies and followers — the question-answer play, early-comment positioning and threads worth reading.',
    tags: ['comments', 'engagement', 'growth', 'followers', 'community'],
    focus: 'strategic commenting',
    angle: 'Here’s a secret hiding in plain sight: on a young network, the best commenters grow faster than the best posters. Comments are borrowed audiences — every trending thread is a stage with the crowd already seated. This guide covers the three comment plays that reliably convert thread readers into your followers.',
  },
  {
    slug: 'peermeld-source-accounts-guide',
    category: 'feed-mastery',
    title: 'Peermeld Source Accounts: freeCodeCamp, Fireship & Friends Explained',
    desc: 'What Source accounts are on Peermeld, the full official list, how the Source badge works, and how to use them for learning and visibility.',
    tags: ['sources', 'freecodecamp', 'fireship', 'curation', 'peermeld feed'],
    focus: 'Peermeld’s Source accounts',
    angle: 'Mixed into your Peermeld feed are badged accounts like freeCodeCamp and Fireship piping in tutorials and release news. They’re not spam and they’re not competitors — they’re the platform’s cold-start solution, and used cleverly they’re also a learning channel and a visibility hack for you.',
  },
  {
    slug: 'peermeld-posting-cadence',
    category: 'feed-mastery',
    title: 'How Often Should You Post on Peermeld? A Practical Cadence Guide',
    desc: 'Daily vs. weekly posting on Peermeld — what the streak system rewards, how cadence affects Trending chances, and a sustainable rhythm for busy builders.',
    tags: ['posting frequency', 'cadence', 'streak', 'consistency', 'content strategy'],
    focus: 'finding your posting cadence',
    angle: 'Post too little and you’re invisible; post filler daily and you train people to skip you. The right cadence on Peermeld is set by two forces most guides ignore: the streak system (which rewards daily presence) and the quality bar of the Trending tab (which punishes noise). Here’s the reconciliation.',
  },
  {
    slug: 'peermeld-60-minute-rule',
    category: 'feed-mastery',
    title: 'The 60-Minute Rule: What to Do Immediately After Posting on Peermeld',
    desc: 'Your post’s first hour decides its fate on Peermeld. The exact post-publish checklist: replies, upvoter engagement, cross-channel drops and timing.',
    tags: ['60 minute rule', 'post launch', 'engagement', 'trending', 'checklist'],
    focus: 'the first hour after you post',
    angle: 'Two identical posts can end with wildly different upvote counts, and the difference is usually what the author did in the first sixty minutes. Trending rewards velocity, and velocity is manufactured in that window. Here’s the minute-by-minute playbook we run after every post that matters.',
  },
  {
    slug: 'peermeld-feed-filters-guide',
    category: 'feed-mastery',
    title: 'Peermeld Feed Filters: Find the Signal in a Growing Network',
    desc: 'How to use Filters on the Peermeld Feed to surface media posts, topics and the content types you care about as the network grows.',
    tags: ['filters', 'peermeld feed', 'discovery', 'productivity', 'curation'],
    focus: 'using Feed Filters effectively',
    angle: 'As Peermeld grows, the firehose grows with it — which makes the Filters control the most underrated button on the page. Whether you’re hunting launch posts with demos or trimming the stream to your niche, this guide shows how to make Filters turn an overwhelming river back into a reading list.',
  },
  {
    slug: 'what-to-post-on-peermeld',
    category: 'feed-mastery',
    title: 'What to Post on Peermeld: 5 Formats the Community Actually Rewards',
    desc: 'The five post formats that dominate Peermeld’s Trending tab — changelogs, build-in-public updates, tool takes, questions and launch posts — dissected.',
    tags: ['what to post', 'post formats', 'trending', 'content strategy', 'builder community'],
    focus: 'the five formats that win the feed',
    angle: 'We classified every Trending post we saw for a month and five formats kept recurring. The list isn’t what you’d predict from other platforms — inspirational content is absent, and the humble numbered changelog is king. Here are the five formats, why each works on this specific audience, and how to execute them.',
  },

  /* ---------------- personal-branding (21–30) ---------------- */
  {
    slug: 'peermeld-profile-seo-guide',
    category: 'personal-branding',
    title: 'Peermeld Profile SEO: Get yourname.peermeld.com Ranking on Google',
    desc: 'The complete SEO guide for your Peermeld subdomain: title tags, bio keywords, freshness signals, backlinks and the built-in SEO preview.',
    tags: ['profile SEO', 'google ranking', 'subdomain', 'personal brand', 'search'],
    focus: 'making your Peermeld profile rank on Google',
    angle: 'Your Peermeld subdomain is a keyword-loaded domain name you got for free — yourname.peermeld.com literally contains the search term people use for you. But the domain is only potential energy; this guide converts it to rankings with the exact content, freshness and backlink moves that work in 2026.',
  },
  {
    slug: 'peermeld-headline-formulas',
    category: 'personal-branding',
    title: '12 Peermeld Headline Formulas That Earn Profile Clicks',
    desc: 'Proven headline templates for your Peermeld profile — role+proof, builder-for-audience, specialist and more — with real examples from the directory.',
    tags: ['headline', 'profile', 'copywriting', 'personal brand', 'directory'],
    focus: 'writing a headline that converts',
    angle: 'Your headline follows you everywhere on Peermeld: directory cards, comment hover cards, search snippets. Twelve words doing a full-time sales job. These twelve formulas cover every career stage — student to founder — each with a fill-in-the-blank template and a real-world example to copy the rhythm from.',
  },
  {
    slug: 'peermeld-gif-banner-ideas',
    category: 'personal-branding',
    title: 'The GIF Banner Advantage: Making Your Peermeld Profile Unforgettable',
    desc: 'Peermeld supports animated GIF banners. Ideas for developer, designer and founder banners that show real work in motion — plus sizing and performance tips.',
    tags: ['banner', 'gif', 'profile design', 'visual identity', 'personal brand'],
    focus: 'using animated banners well',
    angle: 'Scroll the /grow directory and notice which cards you remember an hour later — they’re the ones with motion. Peermeld lets your banner be a GIF, and the best members use it as a product demo, not a decoration. Here are the concepts that work, plus the technical constraints to respect.',
  },
  {
    slug: 'peermeld-bio-examples',
    category: 'personal-branding',
    title: 'How to Write a Peermeld Bio That Converts: 9 Before/After Examples',
    desc: 'Transform your Peermeld bio from filler to funnel — nine rewritten examples showing keyword placement, specificity and the currently-building line.',
    tags: ['bio', 'profile', 'copywriting', 'personal brand', 'examples'],
    focus: 'writing a bio that earns follows',
    angle: 'Bios are where good profiles go to die: vague passions, buzzword soup, no evidence. We took nine typical-before bios and rewrote them using Peermeld’s specific context — the crawlable profile, the directory card, the forty-word attention span. Steal the structures; your bio rewrite should take ten minutes.',
  },
  {
    slug: 'peermeld-personal-brand-90-day-plan',
    category: 'personal-branding',
    title: 'Building a Personal Brand on Peermeld: The 90-Day Plan',
    desc: 'A quarter-by-quarter personal branding plan for Peermeld: weeks 1–4 foundation, 5–8 authority, 9–12 leverage — with daily time budgets and milestones.',
    tags: ['personal brand', '90 day plan', 'strategy', 'growth', 'career'],
    focus: 'a 90-day personal brand build',
    angle: 'Ninety days is the shortest window in which a personal brand visibly changes your life — one job search, one launch, one quarter. This plan compresses everything we know about growing on Peermeld into twelve weeks of daily fifteen-minute actions, with the milestone to expect at the end of each phase.',
  },
  {
    slug: 'rank-peermeld-profile-for-your-name',
    category: 'personal-branding',
    title: 'Google Your Own Name: Getting Your Peermeld Profile to Position #1',
    desc: 'A tactical guide to owning the search results for your name with your Peermeld subdomain — entity consolidation, backlinks, freshness and snippet tuning.',
    tags: ['google ranking', 'name search', 'SEO', 'subdomain', 'reputation'],
    focus: 'owning position one for your name',
    angle: 'Someone will Google you before your next job, client or co-founder chat — that’s not dystopian, it’s just due diligence. The question is whether they find a curated, living page or a scattered mess of stale profiles. Your Peermeld subdomain can own that result; this is the playbook to make it happen.',
  },
  {
    slug: 'peermeld-profile-audit',
    category: 'personal-branding',
    title: 'The 15-Minute Peermeld Profile Audit (Worth Doing Monthly)',
    desc: 'A repeatable monthly audit for your Peermeld presence: search-snippet check, dead-link sweep, headline freshness, tab quality and streak review.',
    tags: ['audit', 'profile', 'maintenance', 'checklist', 'SEO'],
    focus: 'auditing your profile monthly',
    angle: 'Profiles decay silently — links rot, headlines stale, the “currently building” project changes jobs months ago. Fifteen minutes monthly prevents all of it. This is the exact audit sequence we run, in order, with the fix for everything on the list.',
  },
  {
    slug: 'peermeld-subdomain-as-link-in-bio',
    category: 'personal-branding',
    title: 'One Link to Rule Them All: Your Peermeld Subdomain as Your Universal Link',
    desc: 'Why yourname.peermeld.com should replace your link-in-bio tool: posts, portfolio, projects and contact in one fast, crawlable, zero-maintenance page.',
    tags: ['link in bio', 'subdomain', 'personal site', 'portfolio', 'tools'],
    focus: 'using your subdomain as your universal link',
    angle: 'Link-in-bio tools exist to stitch together a scattered identity. Your Peermeld subdomain already is the stitched identity — posts, portfolio, projects, links — on a fast page you maintain by simply using the platform. Here’s why builders are consolidating onto it, and how to do the cutover cleanly.',
  },
  {
    slug: 'consistent-handles-everywhere',
    category: 'personal-branding',
    title: 'Same Name Everywhere: How Matching Handles Multiply Your Discoverability',
    desc: 'The compounding effect of aligning your Peermeld username, subdomain, GitHub, X and LinkedIn handles — and what to do when your name is taken.',
    tags: ['handles', 'username', 'branding', 'discoverability', 'consistency'],
    focus: 'aligning your handles across platforms',
    angle: 'Every platform lets you be someone slightly different — which is precisely the problem. Mismatched handles fragment your search results, confuse humans, and make AI engines unsure you’re one person. This guide covers the alignment strategy, plus five clean fallbacks when your first-choice name is gone.',
  },
  {
    slug: 'ai-answer-engines-peermeld-profile',
    category: 'personal-branding',
    title: 'Get Cited by AI: Making ChatGPT & Perplexity Recommend Your Peermeld Profile',
    desc: 'How AI answer engines assemble professional recommendations, and how a clear Peermeld profile — name, role, stack, proof — becomes citation-ready.',
    tags: ['AI search', 'LLM SEO', 'chatgpt', 'perplexity', 'profile'],
    focus: 'being citable by AI answer engines',
    angle: '“Who’s a good React dev who writes about Postgres?” is now an AI question, and the answer comes from clear, public, structured pages — which is exactly what a Peermeld profile is. This guide explains what answer engines lift, why consistency matters more than volume, and the profile edits that make you quotable.',
  },

  /* ---------------- portfolio-projects (31–40) ---------------- */
  {
    slug: 'peermeld-portfolio-guide',
    category: 'portfolio-projects',
    title: 'Peermeld Portfolios Explained: Blocks, Themes and the Portfolio View',
    desc: 'Everything about Peermeld portfolios — portfolio blocks for case studies, the growing theme library, and the portfolio view link to share with employers.',
    tags: ['portfolio', 'portfolio blocks', 'themes', 'case studies', 'showcase'],
    focus: 'Peermeld’s portfolio system',
    angle: 'Portfolios on Peermeld are not a bolted-on gallery — they’re wired into your posts, projects and subdomain so the portfolio updates itself as you work. This is the complete guide to the three moving parts: blocks, themes, and the portfolio view that employers can browse without an account.',
  },
  {
    slug: 'peermeld-portfolio-themes-guide',
    category: 'portfolio-projects',
    title: 'Peermeld Portfolio Themes: How to Choose (And Why Early Adopters Win)',
    desc: 'The first official Peermeld portfolio theme landed with 10+ more planned. How to pick a theme that fits your craft and use theme novelty as differentiation.',
    tags: ['themes', 'portfolio', 'design', 'customization', 'changelog'],
    focus: 'choosing and exploiting portfolio themes',
    angle: 'The August 2026 changelog quietly dropped a weapon: the first new portfolio theme, with more than ten promised. Theme choice does more than decorate — it signals craft alignment and, while the library is young, early adoption is free differentiation. Here’s how to choose and when to switch.',
  },
  {
    slug: 'peermeld-project-showcase-guide',
    category: 'portfolio-projects',
    title: 'How to Create a Project Showcase on Peermeld That Gets You Hired',
    desc: 'Build a Peermeld project page that converts: naming, taglines, stack tags, screenshots, live links, status honesty and the build-log companion.',
    tags: ['project showcase', 'projects', 'tech stack', 'hiring', 'portfolio'],
    focus: 'creating project pages that convert',
    angle: 'A project page is read in forty-five seconds by someone deciding whether you can build. That reader does not need your life story — they need five specific things in a specific order. This guide is a teardown of the elements that make Peermeld project pages convincing, from the name down to the status badge.',
  },
  {
    slug: 'peermeld-tech-stack-tags',
    category: 'portfolio-projects',
    title: 'Tech Stack Tags: Peermeld’s Quiet Recruiting Magnet',
    desc: 'How tech stack tags on Peermeld projects feed Global Search and recruiter filters — which tags to choose, how many, and the honesty rule that pays.',
    tags: ['tech stack', 'tags', 'recruiting', 'global search', 'projects'],
    focus: 'using tech stack tags strategically',
    angle: 'Buried in the project form is a field that quietly decides whether recruiters ever see you: tech stack tags. They feed Global Search, the filters, and the mental model of everyone who skims your page. This guide covers which tags actually get searched, how many to use, and why honest tagging beats aspirational tagging.',
  },
  {
    slug: 'peermeld-build-logs-guide',
    category: 'portfolio-projects',
    title: 'Build Logs on Peermeld: Write Your Way to a Reputation',
    desc: 'How Peermeld build logs work — the markdown editor, instant preview, sharing to the feed — and why weekly logs outperform every portfolio trick.',
    tags: ['build logs', 'writing', 'markdown', 'build in public', 'projects'],
    focus: 'writing build logs that build reputation',
    angle: 'The most persuasive sentence in tech hiring is “I’ll show you my thinking” — and build logs are literally that, serialised. Peermeld gave them a markdown editor, instant preview and a feed distribution channel. This guide is the case for making weekly logs your primary reputation engine.',
  },
  {
    slug: 'peermeld-build-log-template',
    category: 'portfolio-projects',
    title: 'The Perfect Build Log Template (Steal It for Your Peermeld Projects)',
    desc: 'A reusable Peermeld build log template — Context, Changes, Decisions, Next — with a filled example and the word counts that keep readers to the end.',
    tags: ['build log', 'template', 'writing', 'markdown', 'documentation'],
    focus: 'a build log template that works',
    angle: 'Great logs are structural, not literary — the same four sections every week, executed honestly. Here is the exact template we use, a fully worked example, and the guardrails (section word budgets, the specificity test) that keep logs readable when you’re tired.',
  },
  {
    slug: 'peermeld-portfolio-vs-traditional-sites',
    category: 'portfolio-projects',
    title: 'Peermeld Portfolio Blocks vs. Building Your Own Portfolio Site',
    desc: 'Custom-coded portfolio vs. Peermeld portfolio view — an honest comparison of speed, SEO, maintenance cost and credibility for job seekers in 2026.',
    tags: ['portfolio site', 'comparison', 'custom website', 'job search', 'tools'],
    focus: 'Peermeld versus a hand-built portfolio site',
    angle: 'Every builder faces the dilemma: hand-roll a portfolio site (fun! endless! never finished!) or use a platform (fast, but is it “real”?). Having done both, here is the honest accounting — and the hybrid answer that gives you Peermeld’s maintenance-free portfolio plus the pride of one page you coded yourself.',
  },
  {
    slug: 'peermeld-case-study-writing',
    category: 'portfolio-projects',
    title: 'Writing Case Studies for Peermeld Portfolio Blocks (With the STAR Twist)',
    desc: 'Turn portfolio blocks into interview-winning case studies: problem, role, decisions, outcome — plus the metrics recruiters scan for and screenshot tests.',
    tags: ['case study', 'portfolio', 'writing', 'interviews', 'storytelling'],
    focus: 'writing portfolio case studies',
    angle: 'A portfolio block with a case study is worth ten with screenshots alone, because recruiters forward stories, not images. The twist that makes case studies sing on Peermeld: write them STAR-shaped (Situation, Task, Action, Result) so they double as interview answers. Here’s the structure with worked examples.',
  },
  {
    slug: 'peermeld-open-source-showcase',
    category: 'portfolio-projects',
    title: 'How to Showcase Open Source Work on Peermeld (Issues, PRs, Maintaining)',
    desc: 'Present open source contributions on Peermeld — from your first merged PR to maintaining — with project pages, build logs and the Open Source launch tag.',
    tags: ['open source', 'contributions', 'portfolio', 'maintainers', 'projects'],
    focus: 'showcasing open source work',
    angle: 'Open source is the strongest proof-of-work there is, and the worst-presented. “Contributed to various projects” convinces nobody; a Peermeld project page with your PR narrative, a build log on the gnarly issue you closed, and (yes) a Launch entry for your own tools absolutely does. The full presentation strategy inside.',
  },
  {
    slug: 'peermeld-side-projects-career-capital',
    category: 'portfolio-projects',
    title: 'Turn Side Projects into Career Capital on Peermeld',
    desc: 'Your weekend projects are career assets waiting to be structured. The Peermeld system for documenting, launching and compounding side project value.',
    tags: ['side projects', 'career', 'indie hacking', 'portfolio', 'growth'],
    focus: 'converting side projects into career capital',
    angle: 'That half-finished side project in your repos folder is worth more than most certificates on your CV — once it has a name, a page, a story. This guide is about the conversion ritual: one evening per project structuring your past tinkering into Peermeld’s three proof surfaces.',
  },

  /* ---------------- launch-strategy (41–50) ---------------- */
  {
    slug: 'peermeld-launch-explained',
    category: 'launch-strategy',
    title: 'Peermeld Launch Explained: The Weekly Product Leaderboard for Builders',
    desc: 'How peermeld.com/launch works — weekly cycles, upvotes, TOP rankings, product cards and category tags — plus real entries and why small teams win here.',
    tags: ['peermeld launch', 'leaderboard', 'product launch', 'weekly', 'upvotes'],
    focus: 'the Launch leaderboard mechanics',
    angle: 'Most launch platforms are lotteries where three thousand products fight for one daily spotlight. Peermeld runs a different game: a weekly board, builder-only voters, and rankings a solo dev can win with genuine community support. This is the complete reference to how the board works.',
  },
  {
    slug: 'rank-1-on-peermeld-launch',
    category: 'launch-strategy',
    title: 'How to Rank #1 on Peermeld Launch: The Full Week-by-Week Playbook',
    desc: 'The complete Peermeld Launch campaign: 2-week warm-up, submission timing, launch-day checklist, mid-week momentum and post-launch compounding.',
    tags: ['launch playbook', 'rank 1', 'peermeld launch', 'campaign', 'growth'],
    focus: 'ranking first on the Launch board',
    angle: 'We reverse-engineered what wins Peermeld’s leaderboard — including the platform’s own TOP 1 playbook — and the answer is boring in the best way: planned warm-ups, responsive launch days and honest follow-through. This is the week-by-week campaign template, ready to copy.',
  },
  {
    slug: 'peermeld-launch-vs-product-hunt',
    category: 'launch-strategy',
    title: 'Peermeld Launch vs. Product Hunt: Why a Smaller Board Can Be a Bigger Win',
    desc: 'An honest Peermeld Launch vs. Product Hunt comparison — audience quality, winnability, compounding benefits and when to use both for a product debut.',
    tags: ['product hunt', 'comparison', 'launch platforms', 'indie hackers', 'distribution'],
    focus: 'choosing between launch platforms',
    angle: 'Product Hunt is the giant; Peermeld’s weekly board is the upstart with a structural secret: low-double-digit upvotes have topped its rankings, and every voter is a builder who can become a user, contributor or collaborator. Here is the fair comparison — including exactly when Product Hunt still wins.',
  },
  {
    slug: 'peermeld-launch-day-checklist',
    category: 'launch-strategy',
    title: 'The Peermeld Launch Day Checklist: 14 Steps From Submit to Spotlight',
    desc: 'A printable launch-day checklist for Peermeld: assets, submission, feed announcement, comment hosting, upvoter follow-ups and the evening review.',
    tags: ['launch checklist', 'launch day', 'checklist', 'peermeld launch', 'execution'],
    focus: 'executing a flawless launch day',
    angle: 'Launch days are chaotic; checklists are how chaos becomes choreography. These fourteen steps are sequenced to the hour — what to prepare the night before, the morning submission order, the mid-day velocity pushes, and the evening review that sets up the rest of the week.',
  },
  {
    slug: 'peermeld-launch-taglines',
    category: 'launch-strategy',
    title: 'Launch Taglines That Win Upvotes: Lessons From the Peermeld Leaderboard',
    desc: 'Dissecting real Peermeld launch taglines — from an AI fact-checker to a TypeScript slug library — with the formula for writing yours in ten minutes.',
    tags: ['taglines', 'copywriting', 'launch', 'positioning', 'upvotes'],
    focus: 'writing a tagline that earns upvotes',
    angle: 'On the Launch board, your tagline does eighty percent of the selling: ten words beside a logo, competing for a glance. The current leaders show the pattern — concrete verb, specific audience, zero adjectives. This teardown of real leaderboard taglines ends with a timed exercise to write yours.',
  },
  {
    slug: 'peermeld-prelaunch-warmup',
    category: 'launch-strategy',
    title: 'The 2-Week Pre-Launch Warm-Up Every Peermeld Maker Needs',
    desc: 'Launch weeks are won in advance. The 14-day Peermeld warm-up: problem posts, build logs, goodwill deposits and the audience audit before you submit.',
    tags: ['pre-launch', 'warm-up', 'build in public', 'launch strategy', 'preparation'],
    focus: 'the two-week warm-up before you launch',
    angle: 'The saddest pattern on launch boards is the brilliant product submitted cold — no warmup, no base, three upvotes, invisible. Two weeks of deliberate warm-up fixes it: you arrive with people already invested in your problem. Here is the day-by-day plan.',
  },
  {
    slug: 'peermeld-launch-upvote-ethics',
    category: 'launch-strategy',
    title: 'Getting Peermeld Launch Upvotes Without Being Spammy',
    desc: 'The ethical upvote playbook for Peermeld Launch: individual asks, gratitude loops, off-platform imports — and why vote-trading backfires visibly.',
    tags: ['upvotes', 'ethics', 'launch', 'community', 'authenticity'],
    focus: 'earning upvotes the right way',
    angle: 'Peermeld shows upvoter avatars publicly, which means your upvote acquisition strategy is on display — dignity included. The good news: the tactics that work best are also the most honourable. This guide covers the asks that feel good on both sides, and the shortcuts that will haunt you.',
  },
  {
    slug: 'peermeld-launch-categories',
    category: 'launch-strategy',
    title: 'Picking Your Peermeld Launch Categories: AI, DevTools, Open Source & More',
    desc: 'Category tags shape who sees your Peermeld launch. How to choose two or three that match real voter interest — with examples from the live board.',
    tags: ['categories', 'tags', 'launch', 'positioning', 'audience'],
    focus: 'choosing the right launch categories',
    angle: 'Category tags look like filing; they’re actually targeting. “DevTools + Open Source” and “AI + Productivity” reach different Peermeld sub-communities, and the right pairing puts your product in front of voters predisposed to care. Here is how to read the board’s category patterns and pick yours.',
  },
  {
    slug: 'peermeld-launch-retrospective',
    category: 'launch-strategy',
    title: 'Write the Retrospective: Turn One Peermeld Launch into a Month of Content',
    desc: 'The post-launch retrospective is the most underused content asset on Peermeld. The structure that turns your results — good or bad — into audience growth.',
    tags: ['retrospective', 'post-launch', 'content strategy', 'writing', 'lessons'],
    focus: 'mining your launch for lasting content',
    angle: 'Your launch ends; its value doesn’t have to. A well-written retrospective — numbers, mistakes, surprises — reliably out-performs the launch announcement itself, because builder communities reward honesty over victory laps. This is the retro structure that turns one week of launching into a month of upward graph.',
  },
  {
    slug: 'peermeld-weekly-reset-advantage',
    category: 'launch-strategy',
    title: 'Why Peermeld’s Weekly Reset Is a Gift to Small Makers',
    desc: 'Weekly leaderboard cycles change launch strategy completely — multiple shots a year, fast feedback loops and winnable competition. How to exploit the reset.',
    tags: ['weekly reset', 'launch strategy', 'indie makers', 'leaderboard', 'opportunity'],
    focus: 'exploiting the weekly launch cycle',
    angle: 'On one-shot launch platforms, a bad debut can haunt a product for years. Peermeld’s weekly reset flips the risk math: fifty-two fresh boards a year means iteration beats perfection, and small makers can A/B test their way to a TOP 3. Here’s how to plan a multi-launch year.',
  },
];
